In [3]:
%pip install numpy scikit-learn

import numpy as np
from sklearn.model_selection import train_test_split

  Using cached scikit_learn-1.7.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
  Using cached scipy-1.15.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.7.0-cp313-cp313-win_amd64.whl (10.7 MB)
Using cached joblib-1.5.1-py3-none-any.whl (307 kB)
Using cached scipy-1.15.3-cp313-cp313-win_amd64.whl (41.0 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- -----------------

## Creating dataset

In [4]:
x1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [5]:
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x1.shape

(10,)

In [8]:
x1 = x1.reshape(-1,1)

In [9]:
x1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
x1.shape

(10, 1)

In [13]:
x2 = np.array([201,220,233,243,257,269,272,283,299,339])

In [14]:
x2 = x2.reshape(-1,1)

In [34]:
x2

array([[201],
       [220],
       [233],
       [243],
       [257],
       [269],
       [272],
       [283],
       [299],
       [339]])

In [16]:
x3 = np.array([2000, 3550, 2350, 3940, 4000, 50000, 2677, 9765, 8876, 9776]).reshape(-1,1)
x3

array([[ 2000],
       [ 3550],
       [ 2350],
       [ 3940],
       [ 4000],
       [50000],
       [ 2677],
       [ 9765],
       [ 8876],
       [ 9776]])

In [18]:
X = np.hstack((x1,x2,x3))

In [19]:
X

array([[    0,   201,  2000],
       [    1,   220,  3550],
       [    2,   233,  2350],
       [    3,   243,  3940],
       [    4,   257,  4000],
       [    5,   269, 50000],
       [    6,   272,  2677],
       [    7,   283,  9765],
       [    8,   299,  8876],
       [    9,   339,  9776]])

In [20]:
y = np.array([10,20,30,40,50,60,70,80,90,100])
y

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Splitting the Data

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Data Standardization

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc = StandardScaler()

In [30]:
sc.fit(X_train) # Compute the mean and standard deviation to be used for later scaling.


StandardScaler()

In [31]:
X_train_scaled = sc.transform(X_train) # Scaling the data according to the calculated mean and standard deviation

In [32]:
X_train_scaled

array([[ 0.18569534,  0.18159135,  2.59582878],
       [-1.67125804, -1.61451218, -0.56367527],
       [ 0.92847669,  0.55137737, -0.05255967],
       [-0.92847669, -0.76928699, -0.54063722],
       [ 1.67125804,  2.03052146, -0.05183561],
       [-0.18569534, -0.1353681 , -0.43202927],
       [-0.55708601, -0.50515412, -0.43597865],
       [ 0.55708601,  0.26083121, -0.5191131 ]])

# Mean and Standard deviation of Standardized data

In [33]:
X_train_scaled.mean()

np.float64(0.0)

In [34]:
X_train_scaled.std()

np.float64(1.0)

# Standardized the test data

In [35]:
X_test_scaled = sc.transform(X_test)

In [ ]:
X_test_scaled

array([[ 1.29986737,  0.97398997, -0.11107631],
       [-1.29986737, -1.11265973, -0.46164962]])

In [37]:
# Generated By Sabyasachi